### ISSUE TITLE
User Sign Up is open

### ISSUE THREAD

**Issue by pkennedyvt** [aws-samples/aws-waf-dashboard#1]
The login page allows a user to sign up, get a verification code and then have access.  Would probably be best to have the cognito user pool set to "Only Allow Administrators To Create Users".

**Comment by pkennedyvt** [comment]
I can't make a pull request.  Here's what would get added to waf-dashboard.yaml:

`AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True`

So that entire resource would be:
`AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True`

**Comment by tstachlewski** [comment]
Fixed.
