### ISSUE TITLE
Out of date nodejs version

### ISSUE THREAD

**Issue by simonscholey-nasstar** [aws-samples/aws-waf-dashboard#17]
Deployment failing with

Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.

I wasn't able to find how to update this to use a newer version :(

**Comment by yanivsetton** [comment]
+1

**Comment by leodrak** [comment]
things should work now after some updates. Please let us know if you encounter any more issues.

**Comment by yanivsetton** [comment]
@leodrak worked like a charm
thank you

**Comment by leodrak** [comment]
this issue is fixed by upgrading to CDK v2. Closing.
