### ISSUE TITLE
WAFV2 ARN mapping is not correct

### ISSUE THREAD

**Issue by srikarduplo** [aws-samples/aws-waf-dashboard#5]
Region: us-east-1 is hard coded in the ARN, instead we can replace it with os.environ['REGION']
**logWebACLId = "arn:aws:wafv2:us-east-1:" + os.environ['ACCOUNT_ID'] + ":regional/webacl/" + webacl["Name"] + "/" + webacl["Id"];**

**Comment by tstachlewski** [comment]
Good one! Thx! I will modify it next week!

**Comment by tstachlewski** [comment]
Fixed
